### ISSUE TITLE
raml-for-jax-rs --> Java to RAML --> Nullpointer exception

### ISSUE THREAD

**Issue by jaiishankar** [mulesoft-labs/raml-for-jax-rs#131]
MAVEN settings

``` xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>2.3.2</version>
    <configuration>
        <source>1.6</source>
        <target>1.6</target>
    </configuration>
</plugin>
<plugin>
    <version>1.3.4-SNAPSHOT</version>
    <groupId>org.raml.plugins</groupId>
    <artifactId>jaxrs-raml-maven-plugin</artifactId>
    <configuration>
        <sourceDirectory>${basedir}/src/main/java</sourceDirectory>
        <outputFile>${basedir}/target/generated-sources/jaxrs-raml/tests1/api.raml</outputFile>
        <basePackageName>com.testcompany.services.shoppingbag.v1.domain</basePackageName>
        <jaxrsVersion>2.0</jaxrsVersion>
        <useJsr303Annotations>false</useJsr303Annotations>
        <jsonMapper>jackson2</jsonMapper>
        <removeOldOutput>true</removeOldOutput>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>generate-raml</goal>
            </goals>
            <phase>test</phase>
        </execution>
    </executions>
</plugin>
```

When I try to run the mvn clean install i get nullpointer and the trace is the following

[ERROR] Failed to execute goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.4-SNAPSHOT:generate-raml (default) on project shoppingbag.rest.service: Execution default of goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.4-SNAPSHOT:generate-raml failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.4-SNAPSHOT:generate-raml (default) on project shoppingbag.rest.service: Execution default of goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.4-SNAPSHOT:generate-raml failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.4-SNAPSHOT:generate-raml failed.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 19 more
Caused by: java.lang.NullPointerException
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processField(SpoonProcessor.java:611)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processType(SpoonProcessor.java:289)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processTypeReference(SpoonProcessor.java:569)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.fillJAXBType(SpoonProcessor.java:649)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processMethod(SpoonProcessor.java:490)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processType(SpoonProcessor.java:284)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processTypeReference(SpoonProcessor.java:569)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processType(SpoonProcessor.java:268)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processTypeReference(SpoonProcessor.java:569)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processMethod(SpoonProcessor.java:488)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processType(SpoonProcessor.java:284)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.process(SpoonProcessor.java:247)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processPackage(SpoonProcessor.java:236)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processPackage(SpoonProcessor.java:232)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processPackage(SpoonProcessor.java:232)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processPackage(SpoonProcessor.java:232)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processPackage(SpoonProcessor.java:232)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processPackage(SpoonProcessor.java:232)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.processPackage(SpoonProcessor.java:232)
    at org.raml.jaxrs.codegen.spoon.SpoonProcessor.process(SpoonProcessor.java:110)
    at org.raml.jaxrs.codegen.maven.JaxrsRamlCodegenMojo.execute(JaxrsRamlCodegenMojo.java:153)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
    ... 20 more

```
What is the issue? 
```

**Comment by Strandjanet** [comment]
I have exactly the same issue... did you found a solution already?

**Comment by Strandjanet** [comment]
I have exactly the same issue... already found a solution for it?

**Comment by jaiishankar** [comment]
I fixed it by following.
Cloned - raml-java-parser and raml-for-jax-rs in to the workspace and build and use it. Some one has to release a beta or next version so that we can use them in big companies who have policy of not using snapshots.
