### ISSUE TITLE
maven plugin: included schema references are missing .json extension

### ISSUE THREAD

**Issue by MarcMielke** [mulesoft-labs/raml-for-jax-rs#169]
raml input:

``` yaml
schemas:
  - AppDefinition: !include v2/schema/AppDefinition.json
  - Group: !include v2/schema/Group.json
```

command: 

```
mvn -e -Djava.io.tmpdir=/tmp -Dgenerate.from.raml clean install
```

occuring problem:

```
Caused by: java.io.FileNotFoundException: /tmp/1453380437235-0/AppDefinition.json (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:131)
    at java.io.FileInputStream.<init>(FileInputStream.java:87)
    at com.fasterxml.jackson.core.JsonFactory._optimizedStreamFromURL(JsonFactory.java:1414)
    at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:730)
    at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1875)
    at org.jsonschema2pojo.ContentResolver.resolve(ContentResolver.java:65)
```

actually the files are generated, but are missing the .json extension:

ls -la /tmp/1453380437235-0 shows:

```
-rw-r--r--  1 marcmielke  wheel  21760 21 Jan 13:47 AppDefinition
-rw-r--r--  1 marcmielke  wheel   1842 21 Jan 13:47 Group
```

content of these are correct, plugin version is 1.3.4

**Comment by jpbelang** [comment]
2.0, works.
