### ISSUE TITLE
NullPointerException when uses multipart with body

### ISSUE THREAD

**Issue by ysyzygy** [mulesoft-labs/raml-for-jax-rs#207]
I tried to get jax-rs definition from this REST service example https://github.com/albinkjellin/soap-rest-attachments/blob/master/src/main/api/api.raml (autogenerated using a RAML) but it throws an exception:

C:\raml>java -cp C:\raml\raml-to-jax-rs.jar org.raml.jaxrs.codegen.core.Launcher -basePackageName com.somecompany.sample -outputDirectory C:\raml\ -
sourceDirectory C:\raml\
log4j:WARN No appenders could be found for logger (org.raml.parser.visitor.RamlValidationService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.lang.NullPointerException
at org.raml.jaxrs.codegen.core.Generator.addCatchAllFormParametersArgument(Generator.java:630)
at org.raml.jaxrs.codegen.core.Generator.addBodyParameters(Generator.java:545)
at org.raml.jaxrs.codegen.core.Generator.addResourceMethod(Generator.java:294)
at org.raml.jaxrs.codegen.core.Generator.addResourceMethods(Generator.java:252)
at org.raml.jaxrs.codegen.core.Generator.addResourceMethods(Generator.java:227)
at org.raml.jaxrs.codegen.core.Generator.addResourceMethods(Generator.java:240)
at org.raml.jaxrs.codegen.core.Generator.addResourceMethods(Generator.java:240)
at org.raml.jaxrs.codegen.core.Generator.createResourceInterface(Generator.java:211)
at org.raml.jaxrs.codegen.core.Generator.run(Generator.java:190)
at org.raml.jaxrs.codegen.core.Generator.run(Generator.java:127)
at org.raml.jaxrs.codegen.core.Launcher.main(Launcher.java:63)

Regards

**Comment by jstoiko** [comment]
@ysyzygy: there is a new [2.0.0 version in the works](https://github.com/mulesoft-labs/raml-for-jax-rs/tree/release/2.0.0). Feel free to give it a try and update this issue.
