### ISSUE TITLE
Schema extensions lead to NullPointerException

### ISSUE THREAD

**Issue by frl7082** [mulesoft-labs/raml-for-jax-rs#253]
Let's face this imple RAML schema:

```
#%RAML 1.0
title: extends NPE
baseUri: https://foo/bar

mediaType: application/json

types: 
  A: !include model/A.schema.json
     
/foo:
  get:
    responses:
      200:
        body:
          type: A
```

And the json schemas:

A.schema.json

```
{
	"$schema": "http://json-schema.org/draft-03/schema#",
	"type": "object",
	"extends": {
		"$ref": "B.schema.json"
	},
	"properties": {
		"bar": {
			"type": "string"
		}
	}
}
```

B.schema.json

```
{
	"$schema": "http://json-schema.org/draft-03/schema#",
	"type": "object",
	"properties": {
		"foo": {
			"type": "number"
		}
	}
}
```

A `NullPointerException` is thrown, when generationg the Java classes: 

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.raml:raml-to-jaxrs-maven-plugin:2.0.0:generate (default) on project bazz: Error generating Java classes from: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error generating Java classes from: null
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.execute(RamlJaxrsCodegenMojo.java:212)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.jsonschema2pojo.rules.ObjectRule.getSuperSchema(ObjectRule.java:325)
	at org.jsonschema2pojo.rules.ObjectRule.getSuperType(ObjectRule.java:312)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:86)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:66)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:90)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:134)
	at org.raml.jaxrs.generator.JsonSchemaTypeGenerator.output(JsonSchemaTypeGenerator.java:60)
	at org.raml.jaxrs.generator.builders.AbstractTypeGenerator.output(AbstractTypeGenerator.java:27)
	at org.raml.jaxrs.generator.CurrentBuild.generate(CurrentBuild.java:126)
	at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:94)
	at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:74)
	at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:55)
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.execute(RamlJaxrsCodegenMojo.java:210)
	... 22 more
```

**Comment by jpbelang** [comment]
This was attempted in #251.
