### ISSUE TITLE
NPE when @Provider used in class

### ISSUE THREAD

**Issue by kumaranae** [mulesoft-labs/raml-for-jax-rs#260]
Hi Team,

When we use @Provider annotation with a class like below, it throws NPE.

@Provider
public class GeneralExceptionMapper implements ExceptionMapper<Exception> {
// Some implementation
}

and the exception thrown is below,

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.raml:jaxrs-to-raml-maven-plugin:2.0.1-SNAPSHOT:jaxrstoraml (default) on project primehome-nbi-api: Execution default of goal org.raml:jaxrs-to-raml-maven-plugin:2.0.1-SNAPSHOT:jaxrstoraml failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.raml:jaxrs-to-raml-maven-plugin:2.0.1-SNAPSHOT:jaxrstoraml failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
        at com.google.common.base.Joiner.toString(Joiner.java:447)
        at com.google.common.base.Joiner.appendTo(Joiner.java:113)
        at com.google.common.base.Joiner.appendTo(Joiner.java:154)
        at com.google.common.base.Joiner.appendTo(Joiner.java:142)
        at org.raml.utilities.format.Joiner.join(Joiner.java:57)
        at org.raml.jaxrs.parser.analyzers.JerseyAnalyzer.analyze(JerseyAnalyzer.java:80)
        at org.raml.jaxrs.parser.JerseyJaxRsParser.parse(JerseyJaxRsParser.java:73)
        at org.raml.jaxrs.raml.core.OneStopShop.parseJaxRsAndOutputRaml(OneStopShop.java:75)
        at org.raml.jaxrs.plugin.JaxRsToRamlMojo.confinedExecute(JaxRsToRamlMojo.java:120)
        at org.raml.jaxrs.plugin.JaxRsToRamlMojo.execute(JaxRsToRamlMojo.java:77)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
[ERROR]

**Comment by AndreasZaschka** [comment]
same on version 2.0.0

**Comment by jpbelang** [comment]
I have a guy on this :-)  Fix incoming today, unless it's something major.

**Comment by jpbelang** [comment]
PLease check ?

**Comment by kumaranae** [comment]
It worked for me. thanks.
