### ISSUE TITLE
NullPointerException with a certain RAML

### ISSUE THREAD

**Issue by haba713** [mulesoft-labs/raml-for-jax-rs#265]
raml-to-jaxrs-cli throws NullPointerException when I try to generate JAX-RS classes from [this RAML](https://smartship.unifaun.com/rs-extapi/v1/documentation/root-resource-v1.raml) which is downloaded with all the schema files into directory src/main/raml.

```
ramltojaxrs -d src/main/gen-java src/main/raml/root-resource-v1.raml

Exception in thread "main" java.lang.NullPointerException
at org.raml.jaxrs.generator.v08.V08Finder.typesInBodies(V08Finder.java:106)
at org.raml.jaxrs.generator.v08.V08Finder.resourceTypes(V08Finder.java:81)
at org.raml.jaxrs.generator.v08.V08Finder.resourceTypes(V08Finder.java:78)
at org.raml.jaxrs.generator.v08.V08Finder.resourceTypes(V08Finder.java:78)
at org.raml.jaxrs.generator.v08.V08Finder.findTypes(V08Finder.java:59)
at org.raml.jaxrs.generator.CurrentBuild.constructClasses(CurrentBuild.java:259)
at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:106)
at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:72)
at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:55)
at org.raml.jaxrs.ramltojaxrs.Main.main(Main.java:75)
```

I've tested with [2.0.0](https://github.com/mulesoft-labs/raml-for-jax-rs/releases/tag/2.0.0) and HEAD.

**Comment by jpbelang** [comment]
Could you provide a whole example with the problem please ?

**Comment by haba713** [comment]
Do you mean steps to reproduce the issue? They're here:

1. Clone and compile [raml-for-jax-rs 2.0.0](https://github.com/mulesoft-labs/raml-for-jax-rs/releases/tag/2.0.0).
2. Copy https://smartship.unifaun.com/rs-extapi/v1/documentation/root-resource-v1.raml into src/raml
3. Create output directory src/java
4. Execute org.raml.jaxrs.ramltojaxrs.Main with the following arguments:
`-d src/java src/raml/root-resource-v1.raml`
5. See the resulting NPE with stacktrace.

Should I copy also the schema files referred in RAML into src/raml?

**Comment by jpbelang** [comment]
yeah, send everything, like in a zip file.  It'll save me some time.  

Thanks.

**Comment by haba713** [comment]
See the folder raml-to-jaxrs/examples/maven-examples/posti-smartship in [raml-for-jax-rs.zip](https://github.com/mulesoft-labs/raml-for-jax-rs/files/1094824/raml-for-jax-rs.zip)

**Comment by RigoRos** [comment]
Hey,
I'm facing the same issue during generation with [this](https://devportal.yaas.io/services/loyaltymember/v1/api.raml) RAML file.

**Comment by claudemamo** [comment]
Any updates on this issue? I'm having the same problem with version 2.1.0.

**Comment by jpbelang** [comment]
Changed your pom file to have this:
                    <resourcePackage>resources</resourcePackage>
                    <modelPackage>model</modelPackage>

**Comment by jpbelang** [comment]
@RigoRos fixed for your raml.  It was null bodies.

@claudemamo give it a shot.
