### ISSUE TITLE
ClassCastException with recent changes

### ISSUE THREAD

**Issue by kumaranae** [mulesoft-labs/raml-for-jax-rs#269]
Hi Team,

I have patched the changes did for the issue "RuntimeException with Unknown type #256"

Then am getting the below exception,

Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
        at org.raml.emitter.IndentedAppendableEmitter.pickTypeHandler(IndentedAppendableEmitter.java:243)
        at org.raml.emitter.IndentedAppendableEmitter.writeQueryParameters(IndentedAppendableEmitter.java:297)
        at org.raml.emitter.IndentedAppendableEmitter.writeMethod(IndentedAppendableEmitter.java:195)
        at org.raml.emitter.IndentedAppendableEmitter.writeResource(IndentedAppendableEmitter.java:118)
        at org.raml.emitter.IndentedAppendableEmitter.writeResource(IndentedAppendableEmitter.java:122)
        at org.raml.emitter.IndentedAppendableEmitter.writeApi(IndentedAppendableEmitter.java:86)
        at org.raml.emitter.IndentedAppendableEmitter.emit(IndentedAppendableEmitter.java:71)

**Comment by jpbelang** [comment]
I know what this is, it think:

It's related to #247. To pick up the annotation from a type, it needs to be a Class.  We just need an instanceof test.  This was done for one case here:

jaxrs-to-raml/jaxrs-parser/src/main/java/org/raml/jaxrs/parser/model/JerseyJaxRsEntity.java

You could emergency fix it the same way.  I'll fix this tonight.

**Comment by kumaranae** [comment]
I tried but still hitting the same issue. Can you please fix it tonight and share the fix.

Thanks for your quick response and fixes. I really appreciate it.

**Comment by jpbelang** [comment]
I've pushed a quick fix.  If this works for you, I'll make a general fix.

**Comment by kumaranae** [comment]
Now it throws on the below,

Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:196)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
        at org.raml.emitter.plugins.DefaultTypeHandler.writeType(DefaultTypeHandler.java:43)
        at org.raml.jaxrs.emitters.ParameterEmitter.emit(ParameterEmitter.java:52)
        at org.raml.emitter.IndentedAppendableEmitter.writeQueryParameters(IndentedAppendableEmitter.java:311)
        at org.raml.emitter.IndentedAppendableEmitter.writeMethod(IndentedAppendableEmitter.java:197)
        at org.raml.emitter.IndentedAppendableEmitter.writeResource(IndentedAppendableEmitter.java:120)
        at org.raml.emitter.IndentedAppendableEmitter.writeResource(IndentedAppendableEmitter.java:124)
        at org.raml.emitter.IndentedAppendableEmitter.writeApi(IndentedAppendableEmitter.java:88)
        at org.raml.emitter.IndentedAppendableEmitter.emit(IndentedAppendableEmitter.java:73)
        at org.raml.emitter.FileEmitter.emit(FileEmitter.java:59)
        at org.raml.jaxrs.raml.core.OneStopShop.parseJaxRsAndOutputRaml(OneStopShop.java:81)
        at org.raml.jaxrs.plugin.JaxRsToRamlMojo.confinedExecute(JaxRsToRamlMojo.java:120)
        at org.raml.jaxrs.plugin.JaxRsToRamlMojo.execute(JaxRsToRamlMojo.java:77)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more

**Comment by jpbelang** [comment]
Ok:  I went all over the code to cast stuff through a function.
ParameterizedType -> Raw Type
TypeVariable -> Exception.

**Comment by kumaranae** [comment]
It worked like a charm... thanks a ton. I really appreciate it.
