### ISSUE TITLE
IncludeAdditionalProperties false

### ISSUE THREAD

**Issue by giacgbj** [mulesoft-labs/raml-for-jax-rs#291]
The "jsonMapperConfiguration" configuration "includeAdditionalProperties" is read but it seems that is not used. I've tried to set it to false, but the methods are still generated.

**Comment by jpbelang** [comment]
Are you using a jsonschema ?  jsonMapperConfiguration only works with jsonSchema.  

I'll setup a configuration for disable it if you are using raml data types and you need a global shutdown.  Is this correct ?

**Comment by giacgbj** [comment]
Thanks for pointing out that jsonMapperConfiguration only works with jsonschema because I'm not using it :)

That's correct: I need a global switch using RAML data types.

**Comment by jpbelang** [comment]
I just put an example on how you can suppress the addtionalproperties method.  you can do it globally, or locally on a class.  This is done with annotations.

I will do something else, though.  I'll break down the features into little features that you can activate through annotations if you need customizations.

**Comment by giacgbj** [comment]
I tried it but have to indent it like this
```
uses:
  types: types.raml
  ramltojaxrs: ramltojaxrs.raml
(ramltojaxrs.types):
 onTypeCreation: [ org.raml.jaxrs.generator.builders.extensions.SupressAdditionalProperties ]
```
to avoid:
```
Error generating Java classes from: null: [Invalid element { onTypeCreation: Array[org.raml.jaxrs.generator.builders.extensions.SupressAdditionalProperties]
```

and when it's read properly the following error occurs:
```
Error generating Java classes from: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error generating Java classes from: null
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.execute(RamlJaxrsCodegenMojo.java:213)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.IllegalStateException: only classes have super classes, not INTERFACE
	at com.squareup.javapoet.Util.checkState(Util.java:73)
	at com.squareup.javapoet.TypeSpec$Builder.superclass(TypeSpec.java:478)
	at org.raml.jaxrs.generator.builders.extensions.DefaultTypeCopyHandler.handleSuperclass(DefaultTypeCopyHandler.java:77)
	at org.raml.jaxrs.generator.builders.extensions.TypeCopier.copy(TypeCopier.java:78)
	at org.raml.jaxrs.generator.builders.extensions.SupressAdditionalProperties.onType(SupressAdditionalProperties.java:55)
	at org.raml.jaxrs.generator.extension.types.TypeExtension$Composite$1.doElement(TypeExtension.java:45)
	at org.raml.jaxrs.generator.extension.types.TypeExtension$Composite$1.doElement(TypeExtension.java:41)
	at org.raml.jaxrs.generator.extension.AbstractCompositeExtension.runList(AbstractCompositeExtension.java:42)
	at org.raml.jaxrs.generator.extension.types.TypeExtension$Composite.onType(TypeExtension.java:41)
	at org.raml.jaxrs.generator.v10.typegenerators.SimpleInheritanceExtension.runClassExtensions(SimpleInheritanceExtension.java:354)
	at org.raml.jaxrs.generator.v10.typegenerators.SimpleInheritanceExtension.buildDeclaration(SimpleInheritanceExtension.java:255)
	at org.raml.jaxrs.generator.v10.typegenerators.SimpleInheritanceExtension.onType(SimpleInheritanceExtension.java:69)
	at org.raml.jaxrs.generator.v10.typegenerators.SimpleTypeGenerator.output(SimpleTypeGenerator.java:52)
	at org.raml.jaxrs.generator.CurrentBuild.buildTypeTree(CurrentBuild.java:167)
	at org.raml.jaxrs.generator.CurrentBuild.generate(CurrentBuild.java:120)
	at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:94)
	at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:74)
	at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:55)
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.execute(RamlJaxrsCodegenMojo.java:211)
	... 22 more
```

Do you I need to create other SNAPSHOT artifacts besides raml-to-jaxrs-maven-plugin and jaxrs-code-generator (which were sufficient to test the other functionalities you added)?

**Comment by jpbelang** [comment]
I don't think so although I always maven install the whole half project.

Did you look at the raml-defined-example ?  I seems to work for me.

**Comment by giacgbj** [comment]
If I use my ramls inside that project it works. I'd probably need to deploy other artifacts. I'll wait for the release :-)
