### ISSUE TITLE
Failed to execute goal org.raml.jaxrs:jaxrs-to-raml-maven-plugin:2.1.1:jaxrstoraml

### ISSUE THREAD

**Issue by SaeedSatari** [mulesoft-labs/raml-for-jax-rs#329]
Hi friends. 
I'm using "raml-generator-api" in my projet.
In one of the classes that i have byte[ ] fileld that returned.
When i try to build that with maven i have this error :

[ERROR] Failed to execute goal org.raml.jaxrs:jaxrs-to-raml-maven-plugin:2.1.1:jaxrstoraml (default) on project mobile-search: Execution default of goal org.raml.jaxrs:jaxrs-to-raml-maven-plugin:2.1.1:jaxrstoraml failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.raml.jaxrs:jaxrs-to-raml-maven-plugin:2.1.1:jaxrstoraml (default) on project mobile-search: Execution default of goal org.raml.jaxrs:jaxrs-to-raml-maven-plugin:2.1.1:jaxrstoraml failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.raml.jaxrs:jaxrs-to-raml-maven-plugin:2.1.1:jaxrstoraml failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: java.lang.NullPointerException
	at org.raml.jaxrs.parser.source.Utilities.transformIntoPath(Utilities.java:38)
	at org.raml.jaxrs.parser.source.Utilities.getSourceFileRelativePath(Utilities.java:26)
	at org.raml.jaxrs.parser.source.RoasterSourceParser.getDocumentationFor(RoasterSourceParser.java:73)
	at org.raml.jaxrs.parser.model.JerseyJaxRsEntity.getDescription(JerseyJaxRsEntity.java:49)
	at org.raml.jaxrs.converter.model.JaxRsRamlEntity.getDescription(JaxRsRamlEntity.java:51)
	at org.raml.jaxrs.types.RamlType.write(RamlType.java:104)
	at org.raml.jaxrs.types.TypeRegistry.writeAll(TypeRegistry.java:51)
	at org.raml.emitter.IndentedAppendableEmitter.writeTypes(IndentedAppendableEmitter.java:108)
	at org.raml.emitter.IndentedAppendableEmitter.writeApi(IndentedAppendableEmitter.java:92)
	at org.raml.emitter.IndentedAppendableEmitter.emit(IndentedAppendableEmitter.java:74)
	at org.raml.emitter.FileEmitter.emit(FileEmitter.java:59)
	at org.raml.jaxrs.raml.core.OneStopShop.parseJaxRsAndOutputRaml(OneStopShop.java:81)
	at org.raml.jaxrs.plugin.JaxRsToRamlMojo.confinedExecute(JaxRsToRamlMojo.java:120)
	at org.raml.jaxrs.plugin.JaxRsToRamlMojo.execute(JaxRsToRamlMojo.java:77)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 22 more

It seems that raml-generator parser cannot pars byte[ ] type.

Does anyone have a solution for this issue???
thanks.

**Comment by jpbelang** [comment]
release/2.2.0 has a fix for this.  It also sets the format appropriately.
