### ISSUE TITLE
NPE when scanning #%RAML 1.0 Library Typed files

### ISSUE THREAD

**Issue by 2324829** [mulesoft-labs/raml-for-jax-rs#335]
After cloning the repo and building locally (I am unable to locate the plugin byte code jar anywhere), I am unable to successfully run the CodeGenerator task against the Anypoint RAML generated files from my #%RAML 1.0 project(s) that contain Libraries (I’ve attached the small sample project that contains an API, 2 models and 1 library). I am consistently getting the following stack trace: 

Caused by: org.gradle.api.GradleException:Error generating Java classes from: null         at org.raml.jaxrs.gradle.codegen.CodeGeneratorTask.generate(CodeGeneratorTask.groovy:177)         at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)         at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)         ... 61 more Caused by: java.lang.NullPointerException         at org.raml.jaxrs.generator.v10.V10Finder.findTypes(V10Finder.java:58) 

After inspecting jaxrs-code-generator-2.1.1 source, specifically org.raml.jaxrs.generator .RamlScanner.java I can see that my issue results from the following code:
handle(result.getApiV10(), ramlDirectory); on line 65 of RamlScanner

As seen in my attached zip, UserProfile-lib.raml is of type Library yet this code expects a type of API, which will cause subsequent NPE from the exception above.

I am using generateTypesWith=’jaxb’

Version .8 without inheritance works, but introducing the inheritance model of 1.0 is not working for me. Perhaps I am not designing my project ramls correctly? Is there an issue with my Library structure? Perhaps something I need to add to the Library indicating it shouldn’t be processed as an API? Please advise.

Thanks in advance

[UserProfile-V1.zip](https://github.com/mulesoft-labs/raml-for-jax-rs/files/1767698/UserProfile-V1.zip)

**Comment by jpbelang** [comment]
I haven't looked at your example, so this is entirely theoretical.

Are you trying to just generate the types without any resources ?

(I'll look at your example this PM).

**Comment by 2324829** [comment]
Thanks for the quick reply. Correct, the example has an api and 2 types/models, no resource. Are resource(s) required? If so please advise. Thanks

**Comment by jpbelang** [comment]
Ok.  I've checked:  right now, across ramltojaxrs, I use the API object.  Including libraries would be possible, but we are on the edge of releasing 3.0.0, so I'm reluctant to rock the boat.

It might be in 3.0.1.  In the meantime, though, you should know that resources are not required: you can list only types.

That said, a sister [project](https://github.com/mulesoft-labs/raml-java-tools/tree/release/1.0.0) is probably where the work would be a better fit if you are only trying to use a ramltopojo project.

**Comment by 2324829** [comment]
Thanks for your assistance. Just to confirm, the current ramltojaxrs version 2.X does not support the includes/libraries and theres no way to generate JAXB for the following "address?: !include Address.raml" correct? I'll take a look at the sister project, do you know if the includes/libraries are functional there? When do you expect 3.0.1 to release?

**Comment by jpbelang** [comment]
No, not exactly.  We can't read "root" Library elements.  If the library you are reading is included from an api file (that in your case would not contain resources), then it should work.

**Comment by 2324829** [comment]
So within our api.raml we would do something like:
types: 
  Contact : !include types/Contact.raml

That appears to be working, within Contact.raml we have:
address?: !include Address.raml

I can see an Address interface/implementation as an inner interfaces/implementation to the Contact interface/implementation. Is the expected? Anyway to avoid generating inner interfaces/implementation classes?

Thanks for assisting.

**Comment by jpbelang** [comment]
Yes, it's what is expected. Inline types are defined inside their containing types.
