### ISSUE TITLE
Unable to parse library for workaround.entityListType

### ISSUE THREAD

**Issue by frl7082** [mulesoft-labs/raml-for-jax-rs#341]
The workaround library introduced for #325 is not parsable.

> [ERROR] Failed to execute goal org.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.1:generate (default) on project test-api: Error generating Java classes from: null: [Invalid element {
[ERROR] annotationTypes: {
[ERROR] types: {
[ERROR] allowedTargets: Array[TypeDeclaration,API],
[ERROR] properties: {
[ERROR] className?: null
[ERROR] }
[ERROR] },
[ERROR] resources: {
[ERROR] allowedTargets: Array[Resource,Method,Response,API],
[ERROR] properties: {
[ERROR] plugins?: any[]
[ERROR] }
[ERROR] },
[ERROR] methods: {
[ERROR] allowedTargets: Array[Method,API],
[ERROR] properties: {
[ERROR] plugins?: any[]
[ERROR] }
[ERROR] },
[ERROR] responseClasses: {
[ERROR] allowedTargets: Array[Method,API],
[ERROR] properties: {
[ERROR] plugins?: any[]
[ERROR] }
[ERROR] },
[ERROR] responses: {
[ERROR] allowedTargets: Array[Response,API],
[ERROR] properties: {
[ERROR] plugins?: any[]
[ERROR] }
[ERROR] }
[ERROR] }
[ERROR] }. -- C:/Daten/test-api/src/main/resources/raml/libraries/ramltojaxrs.raml [line=2, col=1]]
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.1:generate (default) on project test-api: Error generating Java classes from: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error generating Java classes from: null
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.execute(RamlJaxrsCodegenMojo.java:216)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.raml.jaxrs.generator.GenerationException: [Invalid element {
annotationTypes: {
types: {
allowedTargets: Array[TypeDeclaration,API],
properties: {
className?: null
}
},
resources: {
allowedTargets: Array[Resource,Method,Response,API],
properties: {
plugins?: any[]
}
},
methods: {
allowedTargets: Array[Method,API],
properties: {
plugins?: any[]
}
},
responseClasses: {
allowedTargets: Array[Method,API],
properties: {
plugins?: any[]
}
},
responses: {
allowedTargets: Array[Response,API],
properties: {
plugins?: any[]
}
}
}
}. -- C:/Daten/test-api/src/main/resources/raml/libraries/ramltojaxrs.raml [line=2, col=1]]
	at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:53)
	at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:45)
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.runFile(RamlJaxrsCodegenMojo.java:226)
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.execute(RamlJaxrsCodegenMojo.java:212)
	... 22 more

I use exactly the same ramltojaxrs.raml library as used in the type-torture test.

This is my plugin configuration:

      <plugin>
        <groupId>org.raml.jaxrs</groupId>
        <artifactId>raml-to-jaxrs-maven-plugin</artifactId>
        <version>3.0.1</version>
        <executions>
          <execution>
            <phase>generate-resources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <ramlFile>${project.build.resources[0].directory}/raml/test.raml</ramlFile>
              <resourcePackage>foo.resource</resourcePackage>
              <modelPackage>foo.model</modelPackage>
              <supportPackage>foo.support</supportPackage>
              <generateTypesWith>
                <value>jackson</value>
              </generateTypesWith>
              <jsonMapper>jackson2</jsonMapper>
              <jsonMapperConfiguration>
                <generateBuilders>true</generateBuilders>
                <useLongIntegers>true</useLongIntegers>
              </jsonMapperConfiguration>
              <removeOldOutput>true</removeOldOutput>
              <outputDirectory>C:\Daten\test\target/generated-sources/raml-jaxrs</outputDirectory>
            </configuration>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>org.raml.jaxrs</groupId>
            <artifactId>jaxrs-code-generator</artifactId>
            <version>3.0.1</version>
            <scope>compile</scope>
          </dependency>
        </dependencies>
      </plugin>

Here is my complete Raml:
[raml.zip](https://github.com/mulesoft-labs/raml-for-jax-rs/files/1859077/raml.zip)

When I copy the `annotationTypes` from the library directly into my raml it works (now not in the `uses` property)

**Comment by frl7082** [comment]
Well, I found the problem. Looks like you should not hae a `!include` before the library reference
