### ISSUE TITLE
“Merging not supported for nodes of type NamedTypeExpressionNode and TypeDeclarationNode”

### ISSUE THREAD

**Issue by deduper** [mulesoft-labs/raml-for-jax-rs#354]
I got some RAML that specifies some HTTP status codes in the responses like so (*the RAML here  is simplified from the original, but perfectly representative*)...

----

    #%RAML 1.0
    title: Schmitle.
    version: v0
    protocols: [HTTP]
    baseUri: http://api.deduper.com
    mediaType: application/json

    uses:
      deduper: libs/lib-deduper.raml

    /myResources/{someId}:
      uriParameters:
        someId:
          type: string
  
      get:
        body:
          application/json:
            type: deduper.MyGetRequestType

        responses:
          200:
            body:
              application/json:
                type: deduper.MyResponseType

          400:
            body: 
              application/json:
                type: deduper.MyErrorType
          429:
            body: 
              application/json:
                type: deduper.MyErrorType
          500:
            body: 
              application/json:
                type: deduper.MyErrorType

      post:

        body:
              application/json:
                type: deduper.MyRequestType

        responses: 
          200:     

          400: 
            body:
              application/json:
                 type: deduper.MyErrorType

          429:
            body: 
              application/json:
                 type: deduper.MyErrorType
          500:
            body: 
              application/json:
                 type: deduper.MyErrorType
              
      put:

        body:
              application/json:
                 type: deduper.MyRequestType

        responses:
          200:

          400:
            body: 
              application/json:
                 type: deduper.MyErrorType
          429:
            body: 
              application/json:
                 type: deduper.MyErrorType
          500:
            body: 
              application/json:
                 type: deduper.MyErrorType

----

    MyRequestType:
        properties:
          foo:
            type: string
            pattern: ^[a-zA-Z]{1024}$
            minLength: 1
            maxLength: 1024
            required: true

----
    MyResponseType:
        properties:
          bar:
            type: string
            pattern: ^[a-zA-Z]{1024}$
            minLength: 1
            maxLength: 1024
            required: true

----
    MyErrorType:
        properties:
          bar:
            type: string
            pattern: ^[a-zA-Z]{1024}$
            minLength: 1
            maxLength: 1024
            required: true

----
----

When I run my actual RAML (_of which the above is only representative_) through  *[raml-to-jaxrs-cli utility][1]*, I get the following error from the RAML parser (*I'm using [release version 2.0.0][2]*)...

----
    Exception in thread "main" java.lang.RuntimeException: Merging not supported for nodes of type NamedTypeExpressionNode and TypeDeclarationNode
            at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsMerger.merge(ResourceTypesTraitsMerger.java:64)
            at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsMerger.merge(ResourceTypesTraitsMerger.java:135)
            at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsMerger.merge(ResourceTypesTraitsMerger.java:52)
            at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsMerger.merge(ResourceTypesTraitsMerger.java:135)
            at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsMerger.merge(ResourceTypesTraitsMerger.java:52)
            at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsMerger.merge(ResourceTypesTraitsMerger.java:135)
            at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsMerger.merge(ResourceTypesTraitsMerger.java:52)
            at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsMerger.merge(ResourceTypesTraitsMerger.java:135)
            at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsMerger.merge(ResourceTypesTraitsMerger.java:52)
            at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsMerger.merge(ResourceTypesTraitsMerger.java:135)
            at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsMerger.merge(ResourceTypesTraitsMerger.java:52)
            at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsMerger.merge(ResourceTypesTraitsMerger.java:135)
            at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsMerger.merge(ResourceTypesTraitsMerger.java:52)
            at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsTransformer.applyResourceType(ResourceTypesTraitsTransformer.java:163)
            at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsTransformer.transform(ResourceTypesTraitsTransformer.java:97)
            at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:45)
            at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
            at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
            at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
            at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
            at org.raml.v2.internal.impl.v10.Raml10Builder.runPhases(Raml10Builder.java:114)
            at org.raml.v2.internal.impl.v10.Raml10Builder.build(Raml10Builder.java:93)
            at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:116)
            at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:100)
            at org.raml.v2.api.RamlModelBuilder.buildApi(RamlModelBuilder.java:125)
            at org.raml.v2.api.RamlModelBuilder.buildApi(RamlModelBuilder.java:115)
            at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:66)
            at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:55)
            at org.raml.jaxrs.ramltojaxrs.Main.main(Main.java:75)

----

Confusingly, however, if I comment out the 400, 429 and 500 status codes from the `post` node of `myResources/{someId}`, then the *[raml-to-jaxrs-cli utility's][1]* parser processes the `get` and `put` status codes just fine. The problem is - *even though it parses fine* - the generator does not generate the right Java code for the `post` stuff.  

This is a snippet of the status code-related JAX-RS that the tool ends up generating...

----

    ...
	
    public static GetMyResourcesBySomeIdResponse respond400WithApplicationJson(MyErrorType entity) {
      Response.ResponseBuilder responseBuilder = Response.status(400).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new GetMyResourcesBySomeIdResponse(responseBuilder.build(), entity);
    }

    public static GetMyResourcesBySomeIdResponse respond429WithApplicationJson(MyErrorType entity) {
      Response.ResponseBuilder responseBuilder = Response.status(429).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new GetMyResourcesBySomeIdResponse(responseBuilder.build(), entity);
    }

    public static GetMyResourcesBySomeIdResponse respond500WithApplicationJson(MyErrorType entity) {
      Response.ResponseBuilder responseBuilder = Response.status(500).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new GetMyResourcesBySomeIdResponse(responseBuilder.build(), entity);
    }

    ...
	
    public static PostMyResourcesBySomeIdResponse respond400WithApplicationJson(MyResourcesSomeIdPost400ApplicationJson entity) {
      Response.ResponseBuilder responseBuilder = Response.status(400).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new PostMyResourcesBySomeIdResponse(responseBuilder.build(), entity);
    }

    public static PostMyResourcesBySomeIdResponse respond429WithApplicationJson(MyResourcesSomeIdPost429ApplicationJson entity) {
      Response.ResponseBuilder responseBuilder = Response.status(429).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new PostMyResourcesBySomeIdResponse(responseBuilder.build(), entity);
    }

    public static PostMyResourcesBySomeIdResponse respond500WithApplicationJson(MyResourcesSomeIdPost500ApplicationJson entity) {
      Response.ResponseBuilder responseBuilder = Response.status(500).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new PostMyResourcesBySomeIdResponse(responseBuilder.build(), entity);
    }

	...
	
    public static PutMyResourcesBySomeIdResponse respond400WithApplicationJson(MyErrorType entity) {
      Response.ResponseBuilder responseBuilder = Response.status(400).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new PutMyResourcesBySomeIdResponse(responseBuilder.build(), entity);
    }

    public static PutMyResourcesBySomeIdResponse respond429WithApplicationJson(MyErrorType entity) {
      Response.ResponseBuilder responseBuilder = Response.status(429).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new PutMyResourcesBySomeIdResponse(responseBuilder.build(), entity);
    }

    public static PutMyResourcesBySomeIdResponse respond500WithApplicationJson(MyErrorType entity) {
      Response.ResponseBuilder responseBuilder = Response.status(500).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new PutMyResourcesBySomeIdResponse(responseBuilder.build(), entity);
    }			

---- 

So here's my question: ***What do I need to do to make the [raml-to-jaxrs-cli utility's][1] parser process the error-related status codes of my `post` node successfully?***

I'd be grateful for a supplementary explanation for why the parser chokes only on the `post` status codes too. Please?

TIA

  [1]: https://github.com/mulesoft-labs/raml-for-jax-rs/blob/master/raml-to-jaxrs/README.md#user-content-using-the-cli
  [2]: https://repository-master.mulesoft.org/nexus/content/repositories/releases/org/raml/jaxrs-to-raml-cli/2.0.0/

**Comment by jpbelang** [comment]
This is a parser issue.  Let me check something, I'll get right back to you...

**Comment by jpbelang** [comment]
Since I'm not getting the error, I also don't quite see what the problem is with your post responses.
