### ISSUE TITLE
jaxrs-to-raml-cli throwing NoSuchMethodError

### ISSUE THREAD

**Issue by shamilchoudhury** [mulesoft-labs/raml-for-jax-rs#364]
Getting `NoSuchMethodError` when trying from command line

```
13:21:47.583 [main] INFO  o.r.jaxrs.parser.JerseyJaxRsParser - parsing JaxRs resource: /home/workspace/build/srccmpfiles
13:21:47.643 [main] DEBUG o.r.jaxrs.parser.JerseyJaxRsParser - found JaxRs related classes: 
[]
13:21:47.646 [main] DEBUG o.r.j.p.analyzers.JerseyAnalyzer - analyzing...
13:21:47.649 [main] DEBUG o.r.j.p.analyzers.JerseyAnalyzer - found jersey resources: 
[]
13:21:47.653 [main] DEBUG o.r.j.p.analyzers.JerseyAnalyzer - found runtime resources: 
[]
13:21:47.656 [main] DEBUG o.r.j.converter.JaxRsToRamlConverter - converting application: 
org.raml.jaxrs.parser.model.JerseyJaxRsApplication@20e2cbe0
Exception in thread "main" java.lang.NoSuchMethodError: org.raml.v2.internal.impl.commons.phase.RamlFragmentGrammarTransformer.<init>(Lorg/raml/v2/internal/impl/v10/Raml10Builder;Lorg/raml/v2/api/loader/ResourceLoader;)V
        at org.raml.builder.Util.createPhases(Util.java:75)
        at org.raml.builder.Util.buildModel(Util.java:55)
        at org.raml.builder.RamlDocumentBuilder.buildModel(RamlDocumentBuilder.java:108)
        at org.raml.emitter.ModelEmitter.emit(ModelEmitter.java:94)
        at org.raml.emitter.FileEmitter.emit(FileEmitter.java:56)
        at org.raml.jaxrs.raml.core.OneStopShop.parseJaxRsAndOutputRaml(OneStopShop.java:82)
        at org.raml.jaxrs.cli.Main.main(Main.java:102)
```

**Comment by jpbelang** [comment]
Which version are you using?

**Comment by shamilchoudhury** [comment]
This is my `pom.xml`

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.raml.jaxrs</groupId>
        <artifactId>jaxrs-to-raml</artifactId>
        <version>3.0.3</version>
    </parent>

    <artifactId>jaxrs-to-raml-cli</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.raml.jaxrs</groupId>
            <artifactId>jaxrs-to-raml-core</artifactId>
        </dependency>
        <!-- logging -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.1.7</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.1.7</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-cli</groupId>
            <artifactId>commons-cli</artifactId>
            <version>1.3.1</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>org.raml.jaxrs.cli.Main</mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by jpbelang** [comment]
I'll look at it this weekend, for sure. It looks like so.ethi g is using g the wrong version of the parser.

**Comment by jpbelang** [comment]
I had left a bad tool version in (what was probably overridden for the maven plugin.  I'm pushing the code as I write.  You should try version 3.0.4-SNAPSHOT using the mulesoft repo.
