### ISSUE TITLE
ClassCastException during jsonschema2pojo [versions 3.0.* ]

### ISSUE THREAD

**Issue by edwmamedov** [mulesoft-labs/raml-for-jax-rs#367]
Caused by: java.lang.ClassCastException: com.sun.codemodel.JFieldVar cannot be cast to com.sun.codemodel.JDocCommentable
        at org.jsonschema2pojo.rules.NotRequiredRule.apply(NotRequiredRule.java:35)
        at org.jsonschema2pojo.rules.PropertyRule.propertyAnnotations(PropertyRule.java:143)
        at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:86)
        at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:43)
        at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:70)
        at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:38)
        at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:119)
        at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:70)
        at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:90)
        at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:66)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
        at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:92)
        at org.raml.jaxrs.generator.JsonSchemaTypeGenerator.output(JsonSchemaTypeGenerator.java:74)
        at org.raml.jaxrs.generator.builders.AbstractTypeGenerator.output(AbstractTypeGenerator.java:27)
        at org.raml.jaxrs.generator.CurrentBuild.generate(CurrentBuild.java:170)
        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:107)
        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:57)
        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:45)
        at org.raml.jaxrs.generator.RamlScanner$handle.call(Unknown Source)
        at org.raml.jaxrs.gradle.codegen.CodeGeneratorTask$_generate_closure1.doCall(CodeGeneratorTask.groovy:141)
        at org.raml.jaxrs.gradle.codegen.CodeGeneratorTask.generate(CodeGeneratorTask.groovy:140)
        ... 83 more`

on following json-scheme:
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "urn:jsonschema:com:zzzzz:advisor:domain:entities:Model",
  "additionalProperties": false,
  "properties": {
    "pageNumber": {
      "type": "integer"
    },
    "pageSize": {
      "type": "integer"
    },
    "numberOfPages": {
      "type": "integer"
    },
    "totalNumberOfElements": {
      "type": "integer"
    },
    "page": {
      "type": "array",
      "items": {
        "$schema": "model.res.json"
      }
    }
  }
}

any ideas??

**Comment by jpbelang** [comment]
Looking at this.  It works in maven.  So, it's weird.  Which version are you using ?

I'm building a gradle example.

**Comment by edwmamedov** [comment]
I tried  several versions (3,4) without success. Did you reproduce it, I could provide complete raml-spec

**Comment by jpbelang** [comment]
Yup.  I suspect that the default configuration is not the same.  I'm checking it either tonight or on the weekend.

**Comment by jpbelang** [comment]
Well, even if the configuration is the same, gradle it seems, through it's infinite wisdom, upgrades some dependencies (snakeyaml, for example).  I'm trying to find the way to prevent this.

**Comment by jpbelang** [comment]
Found it!  Should have found it faster. 
There are two codemodel codebases:  the codemodel jar and it's stuffed into the xjc compiler for jaxb (which I need for supporting jaxb).  For former is more recent and backwards compatible.  The one with jaxb is old, and interferes with jsonschema2pojo.  

Quick fix: in your gradle file prefix the classpath, so that the newer version is ahead in the classpath.
```
        classpath "com.sun.codemodel:codemodel:2.6", 'org.raml.jaxrs:raml-to-jaxrs-gradle-plugin:3.0.whatever'
```

I'll fix it in the plugin.
