### ISSUE TITLE
RAML 1.0 - @JsonDeserialize is not present in generated ResponseDelegate and Response classes of the resource.

### ISSUE THREAD

**Issue by gr423** [mulesoft-labs/raml-for-jax-rs#368]
Hi @jpbelang ,

We are using RAML 1.0 with maven plugin (3.0.3 , latest version ) .

From the service we would be returning the wrapper object as per the RAML contract 

The retrun type from the response is EditorialChannels .$PutEditorialChannelsResponse  

But  at the client side we are getting Deserialization exception .

Caused by: com.fasterxml.jackson.databind.JsonMappingException: Cannot find a deserializer for non-concrete Map type [map type; class javax.ws.rs.core.MultivaluedMap, [simple type, class java.lang.String] -> [collection type; class java.util.List, contains [simple type, class java.lang.String]]]
 at [Source: (SequenceInputStream); line: 1, column: 1]

Since we are missing the @JsonDeserialize on the innerclasses of the respurceType , we would be getting this error .

Please could you suggest me the solution here .

Payload returned to client and tried to Deserialize is below 

```
{
  "delegate": {
    "context": {
      "headers": {
        "Content-Type": [
          "application/json"
        ]
      },
      "committingOutputStream": {
        "adaptedOutput": null,
        "streamProvider": null,
        "bufferSize": 0,
        "buffer": null,
        "directWrite": true,
        "isCommitted": false,
        "isClosed": false,
        "closed": false,
        "committed": false
      },
      "entity": {
        "totalRecords": 1,
        "selfSet": [
          "/mas/v1/XXX/YY_1"
        ]
      },
      "entityType": "com.mas.v1.model.PutResponseImpl",
      "entityAnnotations": [],
      "entityStream": {
        "adaptedOutput": null,
        "streamProvider": null,
        "bufferSize": 0,
        "buffer": null,
        "directWrite": true,
        "isCommitted": false,
        "isClosed": false,
        "closed": false,
        "committed": false
      },
      "length": -1,
      "language": null,
      "location": null,
      "lastModified": null,
      "date": null,
      "links": [],
      "mediaType": {
        "type": "application",
        "subtype": "json",
        "parameters": {},
        "wildcardType": false,
        "wildcardSubtype": false
      },
      "entityClass": "com.mas.v1.model.PutResponseImpl",
      "lengthLong": -1,
      "committed": false,
      "entityTag": null,
      "stringHeaders": {
        "Content-Type": [
          "application/json"
        ]
      },
      "acceptableMediaTypes": [
        {
          "type": "*",
          "subtype": "*",
          "parameters": {},
          "q": 1000,
          "quality": 1000,
          "wildcardType": true,
          "wildcardSubtype": true
        }
      ],
      "responseCookies": {},
      "acceptableLanguages": [
        "*"
      ],
      "requestCookies": {},
      "allowedMethods": []
    },
    "status": 200,
    "closed": false,
    "buffered": false,
    "length": -1,
    "language": null,
    "location": null,
    "lastModified": null,
    "date": null,
    "metadata": {
      "Content-Type": [
        "application/json"
      ]
    },
    "entity": {
      "totalRecords": 1,
      "selfSet": [
        "/mas/v1/XXXX/YY_1"
      ]
    },
    "links": [],
    "cookies": {},
    "statusInfo": "OK",
    "mediaType": {
      "type": "application",
      "subtype": "json",
      "parameters": {},
      "wildcardType": false,
      "wildcardSubtype": false
    },
    "entityTag": null,
    "stringHeaders": {
      "Content-Type": [
        "application/json"
      ]
    },
    "allowedMethods": [],
    "headers": {
      "Content-Type": [
        "application/json"
      ]
    }
  },
  "entity": {
    "totalRecords": 1,
    "selfSet": [
      "/mas/v1/XXX/YY_1"
    ]
  },
  "length": -1,
  "language": null,
  "location": null,
  "lastModified": null,
  "date": null,
  "headers": {
    "Content-Type": [
      "application/json"
    ]
  },
  "status": 200,
  "metadata": {
    "Content-Type": [
      "application/json"
    ]
  },
  "links": [],
  "cookies": {},
  "statusInfo": "OK",
  "mediaType": {
    "type": "application",
    "subtype": "json",
    "parameters": {},
    "wildcardType": false,
    "wildcardSubtype": false
  },
  "entityTag": null,
  "stringHeaders": {
    "Content-Type": [
      "application/json"
    ]
  },
  "allowedMethods": []
}
```

Below is generated interface generated from RAML for resourceType
```
@Path("/editorialChannels")
public interface EditorialChannels {
  /**
   */
  @PUT
  @Produces("application/json")
  @Consumes("application/json")
  PutEditorialChannelsResponse putEditorialChannels(
      @Valid com.nagra.opentv.mas.v1.model.EditorialChannels entity);

  class PutEditorialChannelsResponse extends ResponseDelegate {
    private PutEditorialChannelsResponse(Response response, Object entity) {
      super(response, entity);
    }

    private PutEditorialChannelsResponse(Response response) {
      super(response);
    }

    public static PutEditorialChannelsResponse respond200WithApplicationJson(PutResponse entity) {
      Response.ResponseBuilder responseBuilder = Response.status(200).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new PutEditorialChannelsResponse(responseBuilder.build(), entity);
    }
}
}  
```

**Comment by gr423** [comment]
We need the custom Deserializer for the ResponseDelegate .
Tried creating the custom Deserializer on client , but since it had protected access , not able to create the  custom Deserializer .
Please help me here .

Thanks

**Comment by jpbelang** [comment]
I'm at work right now. I'll look at it tonight.

Why does the client need the custom desrializer? Shouldn't it be magical from a Jackson point of view?

**Comment by gr423** [comment]
Hi,

Since there is no default constructor,it's failing.
Deserailizing since it uses the reflection, it's trying to find the default
constructor which is missing.

So in order to Deserailizing the response delegate we need to register the
custom Deserializer with the ObectMapper.


Thanks and Regards,
Ramya

**Comment by jpbelang** [comment]
Well, that's a response object.  It shouldn't try to deserialize/serialize a reponse object.  It should ont try to serialize the object in the response.

**Comment by gr423** [comment]
Hi,

We are using apache cxf rest client.
Jaxrsclientfactorybean to get the client. Parameter for that would be the
Resource class which gets generated out of Raml.

And when we try to invoke any of the put/delete method, the return type of
it would be the Wrapper Object.,which extends response delegate.


Thanks in advance,
Ramya

**Comment by jpbelang** [comment]
Wait, wait, wait, wait.....I think I've figured out what you are trying to do.  It's wrong, relative to the generated code.

Tell me if this is what is happening: you'd like to have a client that talks to your (fine) jaxrs generated code. You want to use CXF to generate a client.  Unfortunately, CXF does not understand RAML, so you're telling CXF to look at the generated interfaces and asking it to figure out what are the input and output types.

That's not going to work:  the interfaces generated return Response objects:  they are not meant to be serialized, ever.  They are handled by the JAXRS server in a special manner.  JAXRS pulls the entity out of the Response and tries to serialize *that* object.

What you'd like to have is a signature that actually exposes the object you are trying to return.  Such as:

```java
com.mas.v1.model.PutResponse putEditorialChannels( @Valid com.nagra.opentv.mas.v1.model.EditorialChannels entity);
```
(I'm deducing this from the above json, I hope I'm correct).

This would require you to change the code generation process.  Luckily it's doable through a plugin.  It's not a five-minute fix though.  Maybe over the week-end ?  But I need to know this is what you want.

I like the resourcefulness of this attempt at generating a client though.  Kudos. :-)

**Comment by gr423** [comment]
Hi,

Yeah returning putResponse would work for me.
But if calling putEditorialchannels fails for reason, I would have to
return Error Response.

Currently since we are returning a wrapper it's handled.

How can we handle if we just return PutResponse?

Thanks and Regards,
Ramya

**Comment by gr423** [comment]
Hi @jpbelang  , 

The generated class PutEditorialChannelsResponse  is of type ResponseDelegate  ,instead can we just use as a wrapper class for the return type from the service and not extending ResponseDelegate   .

Not sure if the my requirement of Generating the returnType as just a wrapper and not as a response is correct .

Please could you suggest me an alternate which can be used to solve my current situation .

From the service , i'm returning PutEditorialChannelsResponse  object , which is again getting wrapped inside the response . 

Thanks in advance, 
Ramya

**Comment by jpbelang** [comment]
I have a local commit that I have not sufficiently checked.  It *will* be in tonight.

**Comment by jpbelang** [comment]
I don't like my solution, as I'm not totally enforcing the spec through the interface.  I will make it better, but I'm trying to unblock you.  Normally this would be handled by the response.

Here is the solution:  Return types are now types, not responses (with the plugin).  The type returned is either the type of the first 200 or 201 response.  I think I have a problem if you are doing multiple media types.  This is fixable.

I also pass the HttpServletResponse as a parameter, so that you can change the return code.  Tell me if you need this.  How you can use this in in this SO response:

https://stackoverflow.com/questions/4687271/jax-rs-how-to-return-json-and-http-status-code-together

The second response gives examples of how you can return error messages.  The response class is still available, and from this response, you can pull out the entity and the status code.

Tell me if it works.

**Comment by gr423** [comment]
Hi,

We are using lagom framework for providing the rest end points.

Currently the framework takes care of setting the response headers.

So a normal pojo(which would represent entity) would work for me.

Thanks and Regards,
Ramya

**Comment by jpbelang** [comment]
Is it working ?

**Comment by jpbelang** [comment]
Yes, either get a snapshot from the mulesoft repo or download and build the projects (this one and rank java tools)

Or you could get to hear me do my impression of a passive-agressive mother 😁

**Comment by gr423** [comment]
😊Sure I would do it today.

I would defnitely rate the tool 😊

Thank you

**Comment by gr423** [comment]
Hi @jpbelang

Sorry , no luck  .There is no changes to the generated resource class and the return type .
The class generated still extends ResponseDelegate.
I did take the code from branch release/3.0.4 and did install  raml-to-jaxrs to my local repo .
The version changed to 3.0.4-SNAPSHOT .
The code generated is still the same  .
Please could you tell me if I've missed taking some changes.

Thanks in advance,
Ramya

**Comment by gr423** [comment]
I added simpleResponseObjects to the generateType in maven Plugin, getting the exception.
```
<generateTypesWith>
<value>jackson</value>
<value>jsr303</value>
<value>simpleResponseObjects</value>
</generateTypesWith>
```

[ERROR] Failed to execute goal org.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.4-SNAPSHOT:generate (GenerateAdminV2) on project mas-api: Error generating Java classes from: null: Index: 0, Size: 0 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.4-SNAPSHOT:generate (GenerateAdminV2) on project mas-api: Error generating Java classes from: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error generating Java classes from: null
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.execute(RamlJaxrsCodegenMojo.java:216)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:627)
	at org.raml.jaxrs.generator.extension.resources.SimpleResponseObjectExtension.onMethod(SimpleResponseObjectExtension.java:80)
	at org.raml.jaxrs.generator.extension.resources.api.ResourceMethodExtension$Composite$1.doElement(ResourceMethodExtension.java:52)
	at org.raml.jaxrs.generator.extension.resources.api.ResourceMethodExtension$Composite$1.doElement(ResourceMethodExtension.java:48)
	at org.raml.jaxrs.generator.extension.resources.api.AbstractCompositeExtension.runList(AbstractCompositeExtension.java:43)
	at org.raml.jaxrs.generator.extension.resources.api.ResourceMethodExtension$Composite.onMethod(ResourceMethodExtension.java:48)
	at org.raml.jaxrs.generator.builders.resources.ResourceBuilder.createMethodWithoutBody(ResourceBuilder.java:152)
	at org.raml.jaxrs.generator.builders.resources.ResourceBuilder.buildResource(ResourceBuilder.java:99)
	at org.raml.jaxrs.generator.builders.resources.ResourceBuilder.access$400(ResourceBuilder.java:50)
	at org.raml.jaxrs.generator.builders.resources.ResourceBuilder$DefaultResourceClassCreator.onResource(ResourceBuilder.java:660)
	at org.raml.jaxrs.generator.builders.resources.ResourceBuilder.output(ResourceBuilder.java:68)
	at org.raml.jaxrs.generator.CurrentBuild.generate(CurrentBuild.java:184)
	at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:84)
	at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:62)
	at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:45)
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.runFile(RamlJaxrsCodegenMojo.java:226)
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.execute(RamlJaxrsCodegenMojo.java:212)

**Comment by gr423** [comment]
```
<plugin>
				<groupId>org.raml.jaxrs</groupId>
				<artifactId>raml-to-jaxrs-maven-plugin</artifactId>
				<version>3.0.4-SNAPSHOT</version>
				<dependencies>
                    <dependency>
                        <groupId>javax.servlet</groupId>
                        <artifactId>javax.servlet-api</artifactId>
                        <version>4.0.0</version>
                        <scope>compile</scope>
                    </dependency>
                </dependencies>
				<executions>
					<execution>
						<id>GenerateAdminV2</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<phase>generate-sources</phase>
						<configuration>
							<ramlFile>${basedir}/src/main/resources/raml/v1/MAS_api.raml</ramlFile>
							<resourcePackage>com.mas.v1.resource</resourcePackage>
							<modelPackage>com.mas.v1.model</modelPackage>
							<jsonMapper>jackson2</jsonMapper>
							<generateTypesWith>
								<value>jackson</value>
								<value>jsr303</value>
								<value>simpleResponseObjects</value>
							</generateTypesWith>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

**Comment by jpbelang** [comment]
You did it right.  The exception you got is surprising:  on a 200 or 201 response, one of your methods has no @Produces annotation, I suspect.  

I changed it and pushed.  You can try again.

**Comment by gr423** [comment]
sure .
Will pull the latest changes and give a try .

**Comment by gr423** [comment]
This time build is successful .
But the generated class still extends ResponseDelegate.
```
  class PutEditorialChannelsResponse extends ResponseDelegate {
    private PutEditorialChannelsResponse(Response response, Object entity) {
      super(response, entity);
    }

    private PutEditorialChannelsResponse(Response response) {
      super(response);
    }

    public static PutEditorialChannelsResponse respond200WithApplicationJson(
        PutResourceResponse entity) {
      Response.ResponseBuilder responseBuilder = Response.status(200).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new PutEditorialChannelsResponse(responseBuilder.build(), entity);
    }

    public static PutEditorialChannelsResponse respond400WithApplicationJson(
        ErrorBadRequest entity) {
      Response.ResponseBuilder responseBuilder = Response.status(400).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new PutEditorialChannelsResponse(responseBuilder.build(), entity);
    }

    public static PutEditorialChannelsResponse respond500WithApplicationJson(ErrorInternal entity) {
      Response.ResponseBuilder responseBuilder = Response.status(500).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new PutEditorialChannelsResponse(responseBuilder.build(), entity);
    }
  }
```

**Comment by gr423** [comment]
Hi  @jpbelang  ,

Sorry for the confusion  .

The snapshot version generates the model class as the return type from the API.
But classes extending  ResponseDelegate class  is still present in the generated code .
Can we have this wrapper classes , but not extending the ResponseDelegate  is the Generated classes ?

  @PUT
  @Produces("application/json")
  @Consumes("application/json")
  PutResourceResponse putEditorialChannels(
      @Valid com.mas.v1.model.EditorialChannels entity,
      @Context HttpServletResponse httpServletResponse);

Thanks and Regards,
Ramya S

**Comment by gr423** [comment]
The Put API , has multiple response Type , for each of the status codes.

In 3.0.4-Snapshot , on 200 we are giving PutResourceResponse  ,
and the other case , we are generating the Exception .

Instead , can we have the wrapper , which wraps , success as well as  Error .

  collection:    
    put:
      description: Create a new <<resourcePathName|!singularize>>. Unless specified, the <<resourcePathName|!singularize>> ID will be system generated
      body:
        application/json:
          type: <<resourcePathName>>
      responses:
        200:
          description: Created. The request has been fulfilled and has resulted in one or more new resources being created
          body:
            application/json:
              type: putResponse
              example: !include examples/PutResponseExample.json
        400:
          description: Bad Request. The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing)
          body:
            application/json:
              type: errorBadRequest
              example: !include examples/ErrorBadRequestExample.json
        500:
          description: Internal Server Error. The server encountered an unexpected condition that prevented it from fulfilling the request
          body:
            application/json:
              type: errorInternal
              example: !include examples/ErrorInternalExample.json

**Comment by jpbelang** [comment]
You can throw a WebException with a response object as a parameter, if I remember correctly.

**Comment by jpbelang** [comment]
The best solution here would be for you to fool around with a plugin yourself.  I only have a passing knowledge of your requirements.  If you build a pull request off the `org.raml.jaxrs.generator.extension.resources.SimpleResponseObjectExtension` to get it where you want it to be, I can help you to get where you want to go.

**Comment by gr423** [comment]
Hi @jpbelang , 

The code which generates  for "simpleResponse" is  working for us .  Really thankful for the timely help on that . Can we have the release of the same  .

And i just wanted to confirm one thing  , when we add "throwException" it always throws 
Generic Exception   .

Can we have this changed accordingly? say a WebApplicationException.

I was checking for ThrowExceptionsExtension code , it can take the arguments , when mentioned its adding that specific exception to the method definition else Generic Exception .

Please could you tell me how do i pass the arguments here?

Thanks in advance ,
Ramya S

**Comment by jpbelang** [comment]
if it's for methods, the torture test has an example (in general, my examples suck, so I'm happy to point them out) :-)
As a general rule, this is the way you do a plugin with arguments.  If you put it on the API, it should work for all resources.  

```yaml
/jsonThing:
    /bar:
        get:
          (ramltojaxrs.methods):
            plugins:
              - name: ramltojaxrs.throwExceptions
                arguments: [java.lang.Exception]
```

**Comment by gr423** [comment]
Hi Jpbelang  ,

I tried adding the plugin throwExceptions.

Added the plugin in the colletion defined .

```
  collection:    
    put:
      description: Create a new <<resourcePathName|!singularize>>. Unless specified, the <<resourcePathName|!singularize>> ID will be system generated
      body:
        application/json:
          type: <<resourcePathName>>
      (ramltojaxrs.methods):
            plugins:
              - name: ramltojaxrs.throwExceptions
                arguments: [java.lang.Exception]
      responses:
        200:
          description: Created. The request has been fulfilled and has resulted in one or more new resources being created
          body:
            application/json:
              type: putResponse
              example: !include examples/PutResponseExample.json
```

Getting the error .

```
[ERROR] Failed to execute goal org.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.4-SNAPSHOT:generate (GenerateAdminV2) on project mas-api: Error generating Java classes from: null: org.raml.yagi.framework.nodes.ErrorNode cannot be cast to org.raml.yagi.framework.nodes.SimpleTypeNode -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.4-SNAPSHOT:generate (GenerateAdminV2) on project mas-api: Error generating Java classes from: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error generating Java classes from: null
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.execute(RamlJaxrsCodegenMojo.java:216)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.ClassCastException: org.raml.yagi.framework.nodes.ErrorNode cannot be cast to org.raml.yagi.framework.nodes.SimpleTypeNode
	at org.raml.yagi.framework.nodes.ErrorNode.getPath(ErrorNode.java:58)
	at org.raml.v2.internal.impl.commons.model.RamlValidationResult.<init>(RamlValidationResult.java:37)
	at org.raml.v2.api.RamlModelBuilder.generateRamlApiResult(RamlModelBuilder.java:149)
	at org.raml.v2.api.RamlModelBuilder.buildApi(RamlModelBuilder.java:126)
	at org.raml.v2.api.RamlModelBuilder.buildApi(RamlModelBuilder.java:115)
	at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:51)
	at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:45)
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.runFile(RamlJaxrsCodegenMojo.java:226)
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.execute(RamlJaxrsCodegenMojo.java:212)
```

**Comment by jpbelang** [comment]
I think your indenting is wrong, but I can't verify it right now.  I'll try and give you an example tonight.

**Comment by bondars95** [comment]
Hi @jpbelang. When using 
<generateTypesWith>
            <value>simpleResponseObjects</value>
</generateTypesWith>.
Java Primitives are used for query paramaters. _required: false_ option is ignored in raml config.
Could you please help?
