### ISSUE TITLE
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project jaxrs-parser: Ther e are test failures.

### ISSUE THREAD

**Issue by waleyson** [mulesoft-labs/raml-for-jax-rs#383]
Hello,
Please help I was trying to install the raml-for-jaxrs using mvn clean install -U and the failed with the result.

Forking command line: cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_152\jre\bin\java" -jar D:\vault\raml-for-jax-rs-master\jaxrs-to-raml\jaxrs-parser\target\surefire\surefirebooter6
638604423316825106.jar D:\vault\raml-for-jax-rs-master\jaxrs-to-raml\jaxrs-parser\target\surefire\surefire1027170581095379210tmp D:\vault\raml-for-jax-rs-master\jaxrs-to-raml\jaxrs-p
arser\target\surefire\surefire_28955555086244275582tmp"
Running org.raml.jaxrs.parser.gatherers.JerseyGathererTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.579 sec
Running org.raml.jaxrs.parser.model.JerseyJaxRsEntityTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.037 sec
Running org.raml.jaxrs.parser.source.UtilitiesTest
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec <<< FAILURE!
testSimpleClass(org.raml.jaxrs.parser.source.UtilitiesTest)  Time elapsed: 0.001 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<org[\raml\jaxrs\parser\source\]LocalClass.java> but was:<org[/raml/jaxrs/parser/source/]LocalClass.java>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.raml.jaxrs.parser.source.UtilitiesTest.testSimpleClass(UtilitiesTest.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testGenericType(org.raml.jaxrs.parser.source.UtilitiesTest)  Time elapsed: 0.008 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<java[\util\]List.java> but was:<java[/util/]List.java>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.raml.jaxrs.parser.source.UtilitiesTest.testGenericType(UtilitiesTest.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Results :

Failed tests:   testSimpleClass(org.raml.jaxrs.parser.source.UtilitiesTest): expected:<org[\raml\jaxrs\parser\source\]LocalClass.java> but was:<org[/raml/jaxrs/parser/source/]LocalCl
ass.java>
  testGenericType(org.raml.jaxrs.parser.source.UtilitiesTest): expected:<java[\util\]List.java> but was:<java[/util/]List.java>

Tests run: 7, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] raml-for-jaxrs ..................................... SUCCESS [  3.550 s]
[INFO] build-tools ........................................ SUCCESS [  7.490 s]
[INFO] utilities .......................................... SUCCESS [ 11.796 s]
[INFO] jaxrs-to-raml ...................................... SUCCESS [  1.239 s]
[INFO] jaxrs-api .......................................... SUCCESS [  4.141 s]
[INFO] jaxrs-parser ....................................... FAILURE [  9.902 s]
[INFO] raml-api ........................................... SKIPPED
[INFO] jaxrs-to-raml-converter ............................ SKIPPED
[INFO] raml-generator-api ................................. SKIPPED
[INFO] raml-emitter ....................................... SKIPPED
[INFO] jaxrs-to-raml-core ................................. SKIPPED
[INFO] jaxrs-to-raml-cli .................................. SKIPPED
[INFO] jaxrs-to-raml-maven-plugin ......................... SKIPPED
[INFO] jaxrs-to-raml-gradle-plugin-wrapper ................ SKIPPED
[INFO] jaxrs-test-resources ............................... SKIPPED
[INFO] jaxrs-to-raml-examples ............................. SKIPPED
[INFO] jaxrs-to-raml-maven-examples ....................... SKIPPED
[INFO] jaxrs-to-raml-methods .............................. SKIPPED
[INFO] jaxrs-to-raml-types ................................ SKIPPED
[INFO] jaxrs-to-raml-raml-examples ........................ SKIPPED
[INFO] jaxrs-to-raml-annotations .......................... SKIPPED
[INFO] jaxrs-to-raml-multipart ............................ SKIPPED
[INFO] jaxrs-to-raml-gradle-examples ...................... SKIPPED
[INFO] raml-to-jaxrs ...................................... SKIPPED
[INFO] jaxrs-code-generator ............................... SKIPPED
[INFO] raml-to-jaxrs-maven-plugin ......................... SKIPPED
[INFO] raml-to-jaxrs-cli .................................. SKIPPED
[INFO] RAML JAX-RS Gradle Plugin .......................... SKIPPED
[INFO] examples ........................................... SKIPPED
[INFO] maven-examples ..................................... SKIPPED
[INFO] raml-defined-example ............................... SKIPPED
[INFO] jaxb-example ....................................... SKIPPED
[INFO] simple-json-example ................................ SKIPPED
[INFO] simple-xml-example ................................. SKIPPED
[INFO] scalar-types ....................................... SKIPPED
[INFO] simple-raml08 ...................................... SKIPPED
[INFO] multipart .......................................... SKIPPED
[INFO] features ........................................... SKIPPED
[INFO] feature-plugins .................................... SKIPPED
[INFO] feature-raml-project ............................... SKIPPED
[INFO] references ......................................... SKIPPED
[INFO] type-torture-test .................................. SKIPPED
[INFO] RAML To JAX-RS Gradle Examples ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 42.250 s
[INFO] Finished at: 2018-11-24T16:49:11+01:00
[INFO] Final Memory: 37M/511M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project jaxrs-parser: There are test failures.
[ERROR]
[ERROR] Please refer to D:\vault\raml-for-jax-rs-master\jaxrs-to-raml\jaxrs-parser\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project jaxrs-parser: Ther
e are test failures.

**Comment by jpbelang** [comment]
Oh.  It seems to be a windows vs. everybody else. It's not a "real" problem.

You could compile without the tests. I'll see if I could make it better, but it's not a big issue.  They pass on travis.

mvn clean install -DskipTests=true
