### ISSUE TITLE
Deserialization of unions

### ISSUE THREAD

**Issue by coenvl** [mulesoft-labs/raml-for-jax-rs#391]
I have a situation in which I have a data structure in which there is a union of two types, but these types also inherit from the same type.  When I try to deserialize the data the generated deserializer looks at the fields and cannot determine the type, or actually, it incorrectly infers the data is of the first type. However, it should look at the discriminator field. Secondly it uses the incorrect type to construct the object, since it uses the Implementation object, whereas it should use the interface.

The reason why this happens is that the two types in the union have the the same field names, only the _type_ of these fields differ. As a small example take for instance:

```
    BiomeBase:
        discriminator: kind
        type: object
        properties:
            id: integer
            name: string
            kind: string

    Ocean:
        type: BiomeBase
        properties:
            animals: OceanAnimal[]
              
    Jungle:
        type: BiomeBase
        properties:
            animals: JungleAnimal[]
            
    Biome:
        type: Ocean | Jungle
```

This example is fully detailed in my [repository here](https://github.com/coenvl/raml-union-example).

The stacktrace for the first problem looks like this:
```
java.lang.IllegalArgumentException: Class nl.test.example.raml.model.Jungle not subtype of [simple type, class nl.test.example.raml.model.OceanImpl]
	at com.fasterxml.jackson.databind.type.TypeFactory.constructSpecializedType(TypeFactory.java:359)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:185)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:112)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1082)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3600)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3524)
	at nl.test.example.raml.model.Biome$BiomeDeserializer.deserialize(Biome.java:66)
	at nl.test.example.raml.model.Biome$BiomeDeserializer.deserialize(Biome.java:1)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858)
	at nl.test.examplle.RamlExample.main(RamlExample.java:22)
```

And for the second problem, when jackson does try to deserialize the correct type, it looks like this:
```
java.lang.IllegalArgumentException: Class nl.test.example.raml.model.Ocean not subtype of [simple type, class nl.test.example.raml.model.OceanImpl]
	at com.fasterxml.jackson.databind.type.TypeFactory.constructSpecializedType(TypeFactory.java:359)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:185)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:112)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1082)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3600)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3524)
	at nl.test.example.raml.model.Biome$BiomeDeserializer.deserialize(Biome.java:66)
	at nl.test.example.raml.model.Biome$BiomeDeserializer.deserialize(Biome.java:1)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858)
	at nl.test.examplle.RamlExample.main(RamlExample.java:31)
```

**Comment by jpbelang** [comment]
This may be related to this, a bit (https://github.com/mulesoft-labs/raml-for-jax-rs/issues/388), although you are compiling ok.

I'll be looking into this this week.

**Comment by jpbelang** [comment]
But just from a quick look:  the way I figure out union types is I look at the properties by name and try to figure out what type it is.  If two classes have the  same properties it's impossible for me to figure out the proper type.

I'm at work, so I'm just reading....

**Comment by coenvl** [comment]
> This may be related to this, a bit (#388), although you are compiling ok.

It does seem related insofar that in my case there are two "siblings" (in terms of inheritance), that both have a property with a similar name, but different types. However in my case there is no relation between the types of the elements. I might have chosen an incorrect example, because intuitively the JungleAnimal and the OceanAnimal would have a shared parent, which they don't in my original problem.

In the #388 the solution will probably involve relaxing generics, which may be a solution to my second problem, but not the first one. 

> From the raml spec: "Neither discriminator nor discriminatorValue can be defined for any inline type declarations or union types." (these are just notes I'm trying to keep).

I see, so this explains why I cannot add the discriminator to the union (which I tried already). This explains part of the confusion, but it seems then that this is more a corner case in which RAML cannot fully describe what I want instead of a issue of the code generator. 

Currently I have a workaround with a custom serializer, but that means I have to edit the generated code. Is there another way to solve this issue, or should we just change our data model?

**Comment by coenvl** [comment]
I just read from the RAML spec on using discriminators:

> When payloads contain ambiguous types due to **unions** or inheritance, it is often impossible to discriminate the concrete type of an individual object at runtime. For example, when deserializing the payload into a statically typed language, this problem can occur.

However, later it indeed states that on inline unions you cannot use discriminators. Am I then declaring the union the wrong way, or is the specification ambiguous?

**Comment by jpbelang** [comment]
I have an approximate solution.  Does this help ?
