### ISSUE TITLE
Nullpointer Exception in raml-to-jaxrs

### ISSUE THREAD

**Issue by Gana540** [mulesoft-labs/raml-for-jax-rs#394]
Nullpointer Exception while using RAML to JAXB generation. below is the configuration.

<plugin>
                <groupId>org.raml.jaxrs</groupId>
                <artifactId>raml-to-jaxrs-maven-plugin</artifactId>
                <version>3.0.1</version>
                <executions>
                    <execution>
                        <id>1</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <ramlFile>${project.build.resources[0].directory}/Test.raml</ramlFile>
                            <resourcePackage>features.resources</resourcePackage>
                            <modelPackage>features.model</modelPackage>
                            <resourcePackage>features.types</resourcePackage>
                            <generateTypesWith>
                                <value>jaxb</value>
                            </generateTypesWith>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

Error 
[ERROR] Failed to execute goal org.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.1:g
enerate (1) on project jaxb-test : Error generating Java classe
s from: null: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
rg.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.1:generate (1) on project jaxb-test
: Error generating Java classes from: null
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBu
ild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error generating Java
 classes from: null
        at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.execute(RamlJaxrsCo
degenMojo.java:216)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:209)
        ... 19 more
Caused by: java.lang.NullPointerException
        at org.raml.jaxrs.generator.builders.resources.ResourceBuilder.createPar
amteter(ResourceBuilder.java:186)
        at org.raml.jaxrs.generator.builders.resources.ResourceBuilder.createMet
hodWithBody(ResourceBuilder.java:162)
        at org.raml.jaxrs.generator.builders.resources.ResourceBuilder.buildReso
urce(ResourceBuilder.java:107)
        at org.raml.jaxrs.generator.builders.resources.ResourceBuilder.recurse(R
esourceBuilder.java:75)
        at org.raml.jaxrs.generator.builders.resources.ResourceBuilder.access$50
0(ResourceBuilder.java:45)
        at org.raml.jaxrs.generator.builders.resources.ResourceBuilder$DefaultRe
sourceClassCreator.onResource(ResourceBuilder.java:637)
        at org.raml.jaxrs.generator.builders.resources.ResourceBuilder.output(Re
sourceBuilder.java:63)
        at org.raml.jaxrs.generator.CurrentBuild.generate(CurrentBuild.java:184)

        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:84)
        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:62)
        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:45)
        at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.runFile(RamlJaxrsCo
degenMojo.java:226)
        at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.execute(RamlJaxrsCo
degenMojo.java:212)
        ... 21 more

**Comment by jpbelang** [comment]
You are several versions behind:  the last release was 3.0.5, and the code getting a NullPointerException was re-written.  You should try to upgrade.

Could you send me a fragment of raml that fails ?  I'm curious. :-)

**Comment by Gana540** [comment]
Hi, 

I found the route cause of the NPE, but unsure if it is a real issue with RAML or is the plugin missing to handle such scenarios, if the type is defined like a Map with only one type ref mentioned - the plugin doesnt like it and throws and error. do you think the latest version has fixed this ? below is the snippet from RAML that was causing this issue.

body:
         application/json:
         type: [errorTypes.error]

if i change the type to below , it works fine. 
         type: errorTypes.error

Regards,
